// <auto-generated />
using System;
using BlazorDB.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorDB.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230712062724_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorDB.Shared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sss@gmail.com",
                            Name = "Ben",
                            Phone = "0966666666",
                            Position = "engineer",
                            RecordId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sssss@gmail.com",
                            Name = "Alan",
                            Phone = "0977777777",
                            Position = "engineer",
                            RecordId = 2
                        });
                });

            modelBuilder.Entity("BlazorDB.Shared.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PunchIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PunchOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hours = "0",
                            Name = "Ben",
                            PunchIn = new DateTime(2023, 7, 12, 14, 27, 24, 46, DateTimeKind.Local).AddTicks(704),
                            PunchOut = new DateTime(2023, 7, 12, 14, 27, 24, 46, DateTimeKind.Local).AddTicks(705),
                            Time = "2023/07/12"
                        },
                        new
                        {
                            Id = 2,
                            Hours = "0",
                            Name = "Alan",
                            PunchIn = new DateTime(2023, 7, 12, 14, 27, 24, 46, DateTimeKind.Local).AddTicks(714),
                            PunchOut = new DateTime(2023, 7, 12, 14, 27, 24, 46, DateTimeKind.Local).AddTicks(715),
                            Time = "2023/07/12"
                        });
                });

            modelBuilder.Entity("BlazorDB.Shared.Employee", b =>
                {
                    b.HasOne("BlazorDB.Shared.Record", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });
#pragma warning restore 612, 618
        }
    }
}
